disabled_rules:
- void_return
- unavailable_function
- nesting
- closure_end_indentation
- multiple_closures_with_trailing_closure
- file_types_order
- lower_acl_than_parent

opt_in_rules:
- attributes
- closure_end_indentation
- contains_over_first_not_nil
- convenience_type
- direct_return
- discouraged_none_name
- discouraged_object_literal
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_count
- empty_string
- empty_xctest_method
- explicit_acl
- explicit_init
- explicit_top_level_acl
- extension_access_modifier
- file_types_order
- force_unwrapping
- identical_operands
- implicitly_unwrapped_optional
- legacy_random
- local_doc_comment
- lower_acl_than_parent
- missing_docs
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- multiline_parameters_brackets
- no_magic_numbers
- redundant_optional_initialization
- sorted_first_last
- sorted_imports
- strong_iboutlet
- toggle_bool
- unavailable_function
- unused_control_flow_label
- required_enum_case
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call

analyzer_rules:
- capture_variable
- explicit_self
- unused_declaration
- unused_import

force_cast: warning
force_unwrapping: error
force_try: error

#no_magic_numbers:
#  excluded:
#    - ".*Test\\.swift"

identifier_name:
  min_length: 3
  max_length: 50
  allowed_symbols: "_"
  excluded:
    - id
    - dB
    - a
    - b
    - c
    - i
    - j
    - k
    - on

type_name:
  max_length: 60
  allowed_symbols: "_"
  excluded:
    - SwiftUI
    - Mock

line_length: 190

indentation: 2

excluded:
  - Casimir
